/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './makecard.routes';
import * as i2 from './make-list.component.ngfactory';
import * as i3 from './make-edit.component.ngfactory';
import * as i4 from '@angular/router';
import * as i5 from './make-list.component';
import * as i6 from './make-edit.component';
export const MakeCardRoutingModuleNgFactory:i0.NgModuleFactory<i1.MakeCardRoutingModule> = i0.ɵcmf(i1.MakeCardRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MakeListComponentNgFactory,i3.MakeEditComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i4.RouterModule,i4.RouterModule,[[2,i4.ɵa],
          [2,i4.Router]]),i0.ɵmpd(512,i1.MakeCardRoutingModule,i1.MakeCardRoutingModule,
          ([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
        return [[{path:'',redirectTo:'MakeFlashCardsComponent',pathMatch:'full'},{path:'makelist/:id',
            component:i5.MakeListComponent},{path:'edit/:id',component:i6.MakeEditComponent},
            {path:'add',component:i6.MakeEditComponent}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL21ha2UtZmxhc2gtY2FyZHMvbWFrZWNhcmQucm91dGVzLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2xpc2FjL0RvY3VtZW50cy9GbGFzaGNhcmRzL2RldmZjL2ZsYXNoY2FyZHMvYXNzZXRzL2FwcC9tYWtlLWZsYXNoLWNhcmRzL21ha2VjYXJkLnJvdXRlcy50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
