/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.backdrop[_ngcontent-%COMP%] {\r\n	background-color: rgba(0,0,0,0.6);\r\n	position: fixed;\r\n	top: 0;\r\n	left: 0;\r\n	width: 100%;\r\n	height: 100vh;\r\n}\r\n[_nghost-%COMP%] {\r\n	display: flex;\r\n	flex-wrap: wrap;\r\n	margin: auto;\r\n}\r\nh4[_ngcontent-%COMP%] {\r\n	color: black;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL21ha2UtZmxhc2gtY2FyZHMvbWFrZS1kZXRhaWwuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9saXNhYy9Eb2N1bWVudHMvRmxhc2hjYXJkcy9kZXZmYy9mbGFzaGNhcmRzL2Fzc2V0cy9hcHAvbWFrZS1mbGFzaC1jYXJkcy9tYWtlLWRldGFpbC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
