/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.fc-header[_ngcontent-%COMP%] {\r\n    padding: 15px;\r\n    color: white;\r\n    text-align: center;\r\n    align-items: center;\r\n    margin: auto;  \r\n    \r\n    position: fixed;\r\n    top: 3vw;\r\n    right: 0;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL21ha2UtZmxhc2gtY2FyZHMvbWFrZS1mbGFzaC1jYXJkcy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2xpc2FjL0RvY3VtZW50cy9GbGFzaGNhcmRzL2RldmZjL2ZsYXNoY2FyZHMvYXNzZXRzL2FwcC9tYWtlLWZsYXNoLWNhcmRzL21ha2UtZmxhc2gtY2FyZHMuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
