/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app-routing.module';
import * as i2 from './welcome/welcome.component.ngfactory';
import * as i3 from './auth/authentication.component.ngfactory';
import * as i4 from './auth/signup.component.ngfactory';
import * as i5 from './auth/signin.component.ngfactory';
import * as i6 from './auth/logout.component.ngfactory';
import * as i7 from './make-flash-cards/make-flash-cards.component.ngfactory';
import * as i8 from './make-flash-cards/make-list.component.ngfactory';
import * as i9 from './make-flash-cards/make-edit.component.ngfactory';
import * as i10 from './play-flash-cards/play-flash-cards.component.ngfactory';
import * as i11 from './play-flash-cards/deck-list.component.ngfactory';
import * as i12 from './play-flash-cards/deck-play.component.ngfactory';
import * as i13 from '@angular/router';
import * as i14 from '@angular/common';
import * as i15 from './welcome/welcome.component';
import * as i16 from './auth/authentication.component';
import * as i17 from './auth/signup.component';
import * as i18 from './auth/signin.component';
import * as i19 from './auth/logout.component';
import * as i20 from './make-flash-cards/make-flash-cards.component';
import * as i21 from './make-flash-cards/make-list.component';
import * as i22 from './make-flash-cards/make-edit.component';
import * as i23 from './play-flash-cards/play-flash-cards.component';
import * as i24 from './play-flash-cards/deck-list.component';
import * as i25 from './play-flash-cards/deck-play.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.WelcomeComponentNgFactory,i3.AuthenticationComponentNgFactory,i4.SignupComponentNgFactory,
              i5.SigninComponentNgFactory,i6.LogoutComponentNgFactory,i7.MakeFlashCardsComponentNgFactory,
              i8.MakeListComponentNgFactory,i9.MakeEditComponentNgFactory,i10.PlayFlashCardsComponentNgFactory,
              i11.DeckListComponentNgFactory,i12.DeckPlayComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i13.ActivatedRoute,i13.ɵf,[i13.Router]),
          i0.ɵmpd(4608,i13.NoPreloading,i13.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i13.PreloadingStrategy,(null as any),[i13.NoPreloading]),i0.ɵmpd(135680,
              i13.RouterPreloader,i13.RouterPreloader,[i13.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i13.PreloadingStrategy]),i0.ɵmpd(4608,i13.PreloadAllModules,
              i13.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i0.NgProbeToken,() => {
            return [i13.ɵb()];
          },([] as any[])),i0.ɵmpd(4608,i13.ɵg,i13.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i13.ɵh(p0_0)];
              },[i13.ɵg]),i0.ɵmpd(5120,i13.ROUTER_INITIALIZER,i13.ɵi,[i13.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i13.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i13.ɵa,i13.ɵd,[[3,i13.Router]]),
          i0.ɵmpd(512,i13.UrlSerializer,i13.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i13.ChildrenOutletContexts,i13.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i13.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i14.LocationStrategy,
              i13.ɵc,[i14.PlatformLocation,[2,i14.APP_BASE_HREF],i13.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i14.Location,i14.Location,[i14.LocationStrategy]),i0.ɵmpd(512,
              i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i13.ROUTES,() => {
            return [[{path:'',redirectTo:'welcome',pathMatch:'full'},{path:'welcome',
                component:i15.WelcomeComponent},{path:'auth',component:i16.AuthenticationComponent,
                children:[{path:'',redirectTo:'signin',pathMatch:'full'},{path:'signup',
                    component:i17.SignupComponent},{path:'signin',component:i18.SigninComponent},
                    {path:'logout',component:i19.LogoutComponent}]},{path:'makeflashcards',
                component:i20.MakeFlashCardsComponent,children:[{path:'',redirectTo:'MakeFlashCardsComponent',
                    pathMatch:'full'},{path:'makelist/:id',component:i21.MakeListComponent},
                    {path:'edit/:id',component:i22.MakeEditComponent},{path:'add',
                        component:i22.MakeEditComponent}]},{path:'playflashcards',
                component:i23.PlayFlashCardsComponent,children:[{path:'',redirectTo:'PlayFlashCardsComponent',
                    pathMatch:'full'},{path:'decklist',component:i24.DeckListComponent},
                    {path:'decklist/:id',component:i24.DeckListComponent},{path:'play/:id',
                        component:i25.DeckPlayComponent}]}]];
          },([] as any[])),i0.ɵmpd(1024,i13.Router,i13.ɵe,[i0.ApplicationRef,i13.UrlSerializer,
              i13.ChildrenOutletContexts,i14.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i13.ROUTES,i13.ROUTER_CONFIGURATION,[2,i13.UrlHandlingStrategy],
              [2,i13.RouteReuseStrategy]]),i0.ɵmpd(512,i13.RouterModule,i13.RouterModule,
              [[2,i13.ɵa],[2,i13.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL2FwcC1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9saXNhYy9Eb2N1bWVudHMvRmxhc2hjYXJkcy9kZXZmYy9mbGFzaGNhcmRzL2Fzc2V0cy9hcHAvYXBwLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
