/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './welcome/welcome.component.ngfactory';
import * as i4 from './auth/authentication.component.ngfactory';
import * as i5 from './auth/signup.component.ngfactory';
import * as i6 from './auth/signin.component.ngfactory';
import * as i7 from './auth/logout.component.ngfactory';
import * as i8 from './make-flash-cards/make-flash-cards.component.ngfactory';
import * as i9 from './make-flash-cards/make-list.component.ngfactory';
import * as i10 from './make-flash-cards/make-edit.component.ngfactory';
import * as i11 from './play-flash-cards/play-flash-cards.component.ngfactory';
import * as i12 from './play-flash-cards/deck-list.component.ngfactory';
import * as i13 from './play-flash-cards/deck-play.component.ngfactory';
import * as i14 from './app.component.ngfactory';
import * as i15 from '@angular/common';
import * as i16 from '@angular/platform-browser';
import * as i17 from '@angular/forms';
import * as i18 from '@angular/http';
import * as i19 from '@angular/router';
import * as i20 from './errors/error.service';
import * as i21 from './auth/auth.service';
import * as i22 from './shared/deck.service';
import * as i23 from './shared/card.service';
import * as i24 from './shared/utils.service';
import * as i25 from 'angular-2-dropdown-multiselect/dropdown/dropdown.module';
import * as i26 from './welcome/welcome.component';
import * as i27 from './auth/authentication.component';
import * as i28 from './auth/signup.component';
import * as i29 from './auth/signin.component';
import * as i30 from './auth/logout.component';
import * as i31 from './make-flash-cards/make-flash-cards.component';
import * as i32 from './make-flash-cards/make-list.component';
import * as i33 from './make-flash-cards/make-edit.component';
import * as i34 from './play-flash-cards/play-flash-cards.component';
import * as i35 from './play-flash-cards/deck-list.component';
import * as i36 from './play-flash-cards/deck-play.component';
import * as i37 from './app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.WelcomeComponentNgFactory,i4.AuthenticationComponentNgFactory,i5.SignupComponentNgFactory,
              i6.SigninComponentNgFactory,i7.LogoutComponentNgFactory,i8.MakeFlashCardsComponentNgFactory,
              i9.MakeListComponentNgFactory,i10.MakeEditComponentNgFactory,i11.PlayFlashCardsComponentNgFactory,
              i12.DeckListComponentNgFactory,i13.DeckPlayComponentNgFactory,i14.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i15.NgLocalization,i15.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i16.DomSanitizer,i16.ɵe,[i15.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i16.DomSanitizer]),i0.ɵmpd(4608,
              i16.HAMMER_GESTURE_CONFIG,i16.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i16.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i16.ɵDomEventsPlugin(p0_0),new i16.ɵKeyEventsPlugin(p1_0),
                    new i16.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i15.DOCUMENT,i15.DOCUMENT,i15.DOCUMENT,i16.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i16.EventManager,i16.EventManager,[i16.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i16.ɵDomSharedStylesHost,i16.ɵDomSharedStylesHost,
              [i15.DOCUMENT]),i0.ɵmpd(4608,i16.ɵDomRendererFactory2,i16.ɵDomRendererFactory2,
              [i16.EventManager,i16.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,
              (null as any),[i16.ɵDomRendererFactory2]),i0.ɵmpd(6144,i16.ɵSharedStylesHost,
              (null as any),[i16.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,
              i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i16.Meta,i16.Meta,[i15.DOCUMENT]),
          i0.ɵmpd(4608,i16.Title,i16.Title,[i15.DOCUMENT]),i0.ɵmpd(4608,i17.ɵi,i17.ɵi,
              ([] as any[])),i0.ɵmpd(4608,i18.BrowserXhr,i18.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i18.ResponseOptions,i18.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i18.XSRFStrategy,i18.ɵb,([] as any[])),i0.ɵmpd(4608,i18.XHRBackend,
              i18.XHRBackend,[i18.BrowserXhr,i18.ResponseOptions,i18.XSRFStrategy]),
          i0.ɵmpd(4608,i18.RequestOptions,i18.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i18.Http,i18.ɵc,[i18.XHRBackend,i18.RequestOptions]),i0.ɵmpd(4608,i17.FormBuilder,
              i17.FormBuilder,([] as any[])),i0.ɵmpd(5120,i19.ActivatedRoute,i19.ɵf,
              [i19.Router]),i0.ɵmpd(4608,i19.NoPreloading,i19.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i19.PreloadingStrategy,(null as any),[i19.NoPreloading]),i0.ɵmpd(135680,
              i19.RouterPreloader,i19.RouterPreloader,[i19.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i19.PreloadingStrategy]),i0.ɵmpd(4608,i19.PreloadAllModules,
              i19.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i19.ROUTER_INITIALIZER,
              i19.ɵi,[i19.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i19.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i20.ErrorService,i20.ErrorService,
              ([] as any[])),i0.ɵmpd(4608,i21.AuthService,i21.AuthService,[i18.Http,
              i20.ErrorService]),i0.ɵmpd(4608,i22.DeckService,i22.DeckService,[i18.Http,
              i20.ErrorService]),i0.ɵmpd(4608,i23.CardService,i23.CardService,[i18.Http,
              i20.ErrorService]),i0.ɵmpd(4608,i24.UtilsService,i24.UtilsService,([] as any[])),
          i0.ɵmpd(512,i15.CommonModule,i15.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i16.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i19.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i19.ɵg,i19.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i16.ɵc(p0_0,p0_1),i19.ɵh(p1_0)];
              },[[2,i16.NgProbeToken],[2,i0.NgProbeToken],i19.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i16.BrowserModule,i16.BrowserModule,[[3,i16.BrowserModule]]),
          i0.ɵmpd(512,i17.ɵba,i17.ɵba,([] as any[])),i0.ɵmpd(512,i17.FormsModule,i17.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i18.HttpModule,i18.HttpModule,([] as any[])),
          i0.ɵmpd(512,i17.ReactiveFormsModule,i17.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i25.MultiselectDropdownModule,i25.MultiselectDropdownModule,
              ([] as any[])),i0.ɵmpd(1024,i19.ɵa,i19.ɵd,[[3,i19.Router]]),i0.ɵmpd(512,
              i19.UrlSerializer,i19.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i19.ChildrenOutletContexts,i19.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i19.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i15.LocationStrategy,
              i19.ɵc,[i15.PlatformLocation,[2,i15.APP_BASE_HREF],i19.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i15.Location,i15.Location,[i15.LocationStrategy]),i0.ɵmpd(512,
              i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i19.ROUTES,() => {
            return [[{path:'',redirectTo:'welcome',pathMatch:'full'},{path:'welcome',
                component:i26.WelcomeComponent},{path:'auth',component:i27.AuthenticationComponent,
                children:[{path:'',redirectTo:'signin',pathMatch:'full'},{path:'signup',
                    component:i28.SignupComponent},{path:'signin',component:i29.SigninComponent},
                    {path:'logout',component:i30.LogoutComponent}]},{path:'makeflashcards',
                component:i31.MakeFlashCardsComponent,children:[{path:'',redirectTo:'MakeFlashCardsComponent',
                    pathMatch:'full'},{path:'makelist/:id',component:i32.MakeListComponent},
                    {path:'edit/:id',component:i33.MakeEditComponent},{path:'add',
                        component:i33.MakeEditComponent}]},{path:'playflashcards',
                component:i34.PlayFlashCardsComponent,children:[{path:'',redirectTo:'PlayFlashCardsComponent',
                    pathMatch:'full'},{path:'decklist',component:i35.DeckListComponent},
                    {path:'decklist/:id',component:i35.DeckListComponent},{path:'play/:id',
                        component:i36.DeckPlayComponent}]}]];
          },([] as any[])),i0.ɵmpd(1024,i19.Router,i19.ɵe,[i0.ApplicationRef,i19.UrlSerializer,
              i19.ChildrenOutletContexts,i15.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i19.ROUTES,i19.ROUTER_CONFIGURATION,[2,i19.UrlHandlingStrategy],
              [2,i19.RouteReuseStrategy]]),i0.ɵmpd(512,i19.RouterModule,i19.RouterModule,
              [[2,i19.ɵa],[2,i19.Router]]),i0.ɵmpd(512,i37.AppRoutingModule,i37.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
