/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL3BsYXktZmxhc2gtY2FyZHMvZGVjay1wbGF5LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL3BsYXktZmxhc2gtY2FyZHMvZGVjay1wbGF5LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
