/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './flashcard.routes';
import * as i2 from './deck-list.component.ngfactory';
import * as i3 from './deck-play.component.ngfactory';
import * as i4 from '@angular/router';
import * as i5 from './deck-list.component';
import * as i6 from './deck-play.component';
export const FlashcardRoutingModuleNgFactory:i0.NgModuleFactory<i1.FlashcardRoutingModule> = i0.ɵcmf(i1.FlashcardRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.DeckListComponentNgFactory,i3.DeckPlayComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i4.RouterModule,i4.RouterModule,[[2,i4.ɵa],
          [2,i4.Router]]),i0.ɵmpd(512,i1.FlashcardRoutingModule,i1.FlashcardRoutingModule,
          ([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
        return [[{path:'',redirectTo:'PlayFlashCardsComponent',pathMatch:'full'},{path:'decklist',
            component:i5.DeckListComponent},{path:'decklist/:id',component:i5.DeckListComponent},
            {path:'play/:id',component:i6.DeckPlayComponent}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL3BsYXktZmxhc2gtY2FyZHMvZmxhc2hjYXJkLnJvdXRlcy5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9saXNhYy9Eb2N1bWVudHMvRmxhc2hjYXJkcy9kZXZmYy9mbGFzaGNhcmRzL2Fzc2V0cy9hcHAvcGxheS1mbGFzaC1jYXJkcy9mbGFzaGNhcmQucm91dGVzLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
