/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.vertical-center[_ngcontent-%COMP%] {\r\n  min-height: 100%;  \r\n  min-height: 100vh; \r\n\r\n  display: flex;\r\n  align-items: center;\r\n}\r\n\r\nh5[_ngcontent-%COMP%] {\r\n  cursor: pointer;\r\n}\r\nh5[_ngcontent-%COMP%]:hover   span[_ngcontent-%COMP%] {\r\n  color: #6E93F8;\r\n}\r\nh5[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\r\n  text-decoration-line: none;\r\n  color:white;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbGlzYWMvRG9jdW1lbnRzL0ZsYXNoY2FyZHMvZGV2ZmMvZmxhc2hjYXJkcy9hc3NldHMvYXBwL3dlbGNvbWUvd2VsY29tZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2xpc2FjL0RvY3VtZW50cy9GbGFzaGNhcmRzL2RldmZjL2ZsYXNoY2FyZHMvYXNzZXRzL2FwcC93ZWxjb21lL3dlbGNvbWUuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
